In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import random
from sklearn import preprocessing, linear_model as lm, datasets

In [101]:
DataFile = pd.read_csv("hockey_players.csv", delimiter=',', encoding='cp1252')
print(DataFile[:1])

   year country  no              name position side  height  weight  \
0  2001     RUS  10  tverdovsky oleg         D    L     185    84.0   

        birth                   club        age  cohort        bmi  
0  1976-05-18  anaheim mighty ducks   24.952772    1976  24.543462  


In [124]:
x1=[]
for line in DataFile['height']:
    x1.append(float(line))
print(x1[:10])

[185.0, 188.0, 182.0, 178.0, 175.0, 193.0, 176.0, 183.0, 180.0, 178.0]


In [103]:
x2=[]
for line in DataFile['weight']:
    x2.append(line)
print(x2[:10])

[84.0, 86.0, 95.0, 85.0, 88.0, 93.0, 84.0, 91.0, 85.0, 86.0]


In [104]:
x3=[]
for line in DataFile['year']:
    x3.append(line)
print(x3[:10])

[2001, 2001, 2001, 2001, 2001, 2001, 2001, 2001, 2001, 2001]


In [105]:
X = []
for i, line in enumerate(DataFile.values):
    row = [x1[i]]+[x2[i]]
    X.append([1.]+row)
    
for line in X[:1]:
    print(line)

[1.0, 185.0, 84.0]


In [108]:
Y=x3
# for line in DataFile['year']:
#     Y.append(line)
print(Y[:10])

[2001, 2001, 2001, 2001, 2001, 2001, 2001, 2001, 2001, 2001]


In [110]:
norm_X = preprocessing.normalize(X)
print(X[:1])
print(norm_X[:1])

[[1.0, 185.0, 84.0]]
[[ 0.00492175  0.91052393  0.41342708]]


In [111]:
mplier=[max(factor) for factor in X]
new_X=[]
for i, factor in enumerate(X):
    new_X.append([x_i/mplier[i] for x_i in factor])
new_X = np.transpose(new_X)
print(new_X[:1])

[[ 0.00540541  0.00531915  0.00549451 ...,  0.0052356   0.00531915
   0.00518135]]


In [112]:
# B=np.dot(np.dot(np.linalg.inv((np.dot(np.transpose(norm_X),norm_X))),np.transpose(norm_X)),Y)

norm_C = np.dot(np.transpose(norm_X),norm_X)
norm_G = np.linalg.inv(norm_C)
norm_B = np.dot(np.dot(norm_G,np.transpose(norm_X)),Y)
print(norm_B)

[-4053.88570297  1836.41238846   863.10534364]


In [113]:
C = np.dot(np.transpose(X),X)
G = np.linalg.inv(C)
B = np.dot(np.dot(G,np.transpose(X)),Y)
print(B)

[  1.99096132e+03   1.00103061e-01  -9.18715181e-03]


In [121]:
lin = lambda X: np.dot(X,B)
# X_tr=np.dot(X,B)
x_tr=lin(X)
print(x_tr)

[ 2008.70866543  2008.99060032  2008.30729758 ...,  2009.2725352
  2008.96303886  2009.40843126]


In [116]:
plt.figure(figsize=(7,4))
plt.plot()
# plt.plot(x1,x2, 'go')
# plt.show()
# plt.plot(Y,x1, 'go')
# plt.show()
# plt.plot(Y,x2, 'go')
# plt.show()
# plt.plot(Y,X, 'go')
# plt.show()
# plt.plot(Y,norm_X, 'go')
# plt.show()

[]

In [13]:
reg = lm.LinearRegression()
reg.fit(X,Y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [14]:
diabetes=datasets.load_diabetes()
# regr=linear_model.LinearRegression()
skm=lm.LinearRegression()
skm.fit(norm_X,Y)
print (skm.intercept_, skm.coef_)

1798.95998406 [-3661.07349711   209.92219879    88.68915569]
